name: Debug Sudo

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:


# Limit this workflow to a single run at a time per-branch to avoid wasting worker resources
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sudo:
    runs-on: ubuntu-latest

    steps:
      - name: Runner User
        run: |
          if [ "$XDG_CONFIG_HOME" = "/home/runner/.config" ]; then
            echo "✓ Runner XDG_CONFIG_HOME is correctly set to /home/runner/.config"
          else
            echo "✗ Runner XDG_CONFIG_HOME is '$XDG_CONFIG_HOME', expected '/home/runner/.config'"
          fi

          sudo_xdg=$(sudo printenv XDG_CONFIG_HOME || echo "")
          if [ "$sudo_xdg" = "/home/runner/.config" ]; then
            echo "✓ Sudo XDG_CONFIG_HOME is correctly set to /home/runner/.config"
          else
            echo "✗ Sudo XDG_CONFIG_HOME is '$sudo_xdg', expected '/home/runner/.config'"
            exit 1
          fi

      - name: Alternate User
        run: |
          sudo useradd --create-home --shell=/bin/bash example-user
          alt_xdg=$(sudo -u example-user printenv XDG_CONFIG_HOME || echo "")
          if [ "$alt_xdg" != "/home/runner/.config" ]; then
            echo "✓ example-user XDG_CONFIG_HOME is correctly different: '$alt_xdg'"
          else
            echo "✗ example-user XDG_CONFIG_HOME should not be '/home/runner/.config'"
            exit 1
          fi

  uv:
    runs-on: ubuntu-latest

    steps:
      - name: Install uv
        run: |
          sudo useradd --create-home --shell=/bin/bash example-user
          curl -LsSf https://astral.sh/uv/install.sh | sudo -u example-user sh
